name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: feeds update
      run: ./scripts/feeds update -a
    - name: feeds install
      run: ./scripts/feeds install -a
    - name: menuconfig
      run: make menuconfig

